package fsTablesEnums;

/**
 * This enum keeps track of manufacturers
 * 
 * @author Steven Wancewicz
 * @version 2013-5-25
 * 
 */
public enum Make 
{
	//please alphabetize
	AAON("AAON"),
	ABCO("ABCO"),
	ABSOLUTAIRE("AbsolutAire"),
	ACP("ACP"),
	ACPO("ACPO"),
	ADAPT("Adapt"),
	ADDISON("ADDISON"),
	ADIRONDACKAIRE("Adirondack-Aire"),
	ADP("ADP"),
	AEROFLO("Aeroflo"),
	AIRCO("Airco"),
	AIRDALE("Airdale"),
	AIRINNOVATIONS("Air Innovations"),
	AIREASE("Air Ease"),
	AIREFLO("Aire-Flo"),
	AIRPAC("AirPac"),
	AIRQUEST("Airquest"),
	AIRSTAR("Air Star"),
	AIRTEMP("AirTemp"),
	ALLSTYLE("All Style"),
	AMANA("Amana"),
	AMERICANBEST("American Best"),
	AMERICANRADIATOR("American Radiator"),
	AMERICANSTANDARD("American Standard"),
	ANTHESWESTERN("Anthes Western"),
	AQUAPRODUCTS("Aqua Products"),
	ARCOAIRE("Arco-aire"),
	ARGO("ARGO"),
	ARKLA("ARKLA"),
	ARMSTRONGAIR("Armstrong Air"),
	AVENGER("Avenger"),
	AXEMANANDERSON("Axeman-Anderson"),
	BARD("BARD"),
	BARTACO("BARTACO"),
	BASMOR("BASMOR"),
	BDP("BDP"),
	BIASI("BIASI"),
	BORGWARNER("BORG-WARNER"),
	BROAN("Broan"),
	BROCK("Brock"),
	BRYAN("Bryan"),
	BRYANT("Bryant"),
	BUDERUS("Buderus"),
	BURNHAM("Burnham"),
	CALIFORNIAHEATPUMP("California Heat Pump"),
	CANATAL("Canatal"),
	CAPTIVEAIRE("Captive-Aire"),
	CARRIER("Carrier"),
	CENTURY("Century"),
	CHROMALOX("Chromalox"),
	CHRYSLER("Chrysler"),
	CLARE("Clare"),
	CLEAVERBROOKS("Cleaver Brooks"),
	CLIMACOOL("ClimaCool"),
	CLIMATECONTROL("Climate Control"),
	CLIMATEMASTER("ClimateMaster"),
	COLDPOINT("Cold Point"),
	COLEMAN("Coleman"),
	COLUMBIA("Columbia"),
	COMITALENATIONAL("Comitale National"),
	COMFORTAIRE("Comfort Aire"),
	COMFORTMAKER("Comfortmaker"),
	COMMANDAIRE("Command Aire"),
	COMPUAIRE("Compu-Aire"),
	CONCORD("Concord"),
	CONQUEST("Conquest"),
	COOLINE("Cooline"),
	COPELAND("Copeland"),
	CONSOLIDATED("Consolidated"),
	CORSAIRE("Corsaire"),
	COUNTERFLO("Counterflo"),
	CROWN("Crown"),
	DAIKIN("DAIKIN"),
	DATAAIR("Data Air"),
	DAYNIGHT("Day & Night"),
	DAYTON("Dayton"),
	DELTA("Delta"),
	DIRECTFLO("Directflo"),
	DRYAIRE("DryAire"),
	DUCANE("Ducane"),
	DUNKIRK("Dunkirk"),
	DUNHAMBUSH("Dunham-Bush"),
	DUOMATICOLSEN("Duo-matic Olsen"),
	EDPAC("EDPAC"),
	ECR("ECR"),
	ECONAR("ECONAR"),
	ELECTRO("Electro"),
	EMERSON("Emerson"),
	ENTERPRISEFAWCETT("Enterprise Fawcett"),
	ENERGYKINETICS("Energy Kinetics"),
	EVAPCO("Evapco"),
	EVCON("Evcon"),
	EVON("EVON"),
	EXCELSIOR("Excelsior (See Utica)"),
	FEDDERS("Fedders"),
	FHP("FHP"),
	FIRSTCO("First Co."),
	FLORIDAHEATPUMPS("Florida Heat Pumps"),
	FORD("Ford"),
	FRANKLINELECTRIC("Franklin Electric"),
	FRASER("Fraser"),
	FRASERJOHNSTON("Fraser-Johnston"),
	FRIEDRICH("Friedrich"),
	FRIGIDAIRE("Frigidaire"),
	FUJITSU("Fujitsu"),
	GE("GE"),
	GIBSON("Gibson"),
	GLOWCORE("Glowcore"),
	GMC("GMC"),
	GOETTL("Goettl"),
	GOODMAN("Goodman"),
	GOVERNAIRE("Governaire"),
	GRANDAIRE("Grandaire"),
	GRIMSBY("Grimsby"),
	HAIER("Haier"),
	HALLMARK("Hallmark"),
	HAMILTONELECTRIC("Hamilton Electric"),
	HBSMITH("H.B. Smith"),
	HEATCONTROLLER("Heat Controller"),
	HEATMASTER("Heatmaster"),
	HEIL("Heil"),
	HEILQUAKER("Heil-Quaker"),
	HERMANNELSAN("Herman Nelsan"),
	HOLLYGENERAL("Holly General"),
	HONEYWELL("Honeywell"),
	HURRICANE("Hurricane"),
	HYDRAULICSINSTITUTECACBDP("Hydraulics Institute CAC/BDP"),
	HYDROHEAT("Hydro Heat"),
	HYDROTEMP("Hydro Temp"),
	HYDRtHERM("Hydro Therm"),
	HYDRONMODULE("Hydron Module"),
	ICECAPS("Ice-Caps"),
	ICECO("ICECO"),
	ICPCOMMERCIAL("ICP Commercial"),
	INCREMENTAL("Incremental"),
	INTERCITY("Inter City"),
	INTERNATIONALCOMFORTPRODUCTS("International Comfort Products"),
	INTERTHERM("Intertherm"),
	ISLANDAIRE("Islandaire"),
	JANITROL("Janitrol"),
	JOHNSON("Johnson"),
	JOHNSTON("Johnston"),
	JOHNSTONE("Johnstone"),
	KEEPRITE("Keeprite"),
	KELVINATOR("Kelvinator"),
	KENMORE("Kenmore"),
	KENNARDNELSON("Kennard-Nelson"),
	KLIMAIRE("Klimaire"),
	KWIKOOL("KwiKool"),
	LAARS("Laars"),
	LAYTON("Layton"),
	LEARSIEGLER("Lear Siegler"),
	LENDELL("Lendell"),
	LENNOX("Lennox"),
	LIBERTY("Liberty"),
	LIEBERT("Liebert"),
	LINCOLN("Lincoln"),
	LINTERN("Lintern"),
	LOCHINVAR("Lochinvar"),
	LSB("LSB"),
	LUXAIRE("Luxaire"),
	MAGICAIRE("Magic Aire"),
	MAGICCHEF("Magic Chef"),
	MAGICPAK("Magic-Pak"),
	MAMMOTH("Mammoth"),
	MARLEY("Marley"),
	MARVAIR("Marvair"),
	MAYTAG("Maytag"),
	MCQUAY("McQuay"),
	MEAPTRON("Meaptron"),
	MILLER("Miller"),
	MISSION("Mission"),
	MITSUBISHI("Mitsubishi"),
	MOBILEAIR("Mobile Air"),
	MODINE("Modine"),
	MONCREIF("Moncreif (See York)"),
	MONITOR("Monitor"),
	MONTGOMERYWARD("Montgomery Ward"),
	MOTIVAIR("Motivair"),
	MUNCHKIN("Munchkin"),
	NEWMAC("Newmac"),
	NORDICAIR("Nordic Air"),
	NORDYNE("Nordyne"),
	NORTHRUP("Northrup"),
	NORTHSTAR("Northstar"),
	NUTEMP("NuTemp"),
	NUTONE("NuTone"),
	OCEANAIRE("Oceanaire"),
	OLSEN("Olsen"),
	ONEIDAROYAL("Oneida Royal"),
	PFC("PFC"),
	PAMECOAIRE("Pameco-Aire"),
	PARADISE("Paradise"),
	PARKER("Parker"),
	PATRIOT("Patriot"),
	PAYNE("Payne"),
	PEERLESS("Peerless"),
	PENNCO("Pennco"),
	PENSTANAIREASE("Penstan Air-Ease"),
	PHILCO("Philco"),
	POLARIS("Polaris"),
	PREMIE("Premie"),
	QUICKAIRE("Quickaire"),
	QUIETSIDE("Quietside"),
	RAYPACMOTIVAIR("Raypac Motivair"),
	REMINGTON("Remington"),
	REPCO("REPCO"),
	REPUBLIC("Republic"),
	RETROAIRE("Retroaire"),
	REZNOR("Reznor"),
	RHEEM("Rheem"),
	RIELLO("Riello"),
	RINNAI("Rinnai"),
	RITETEMP("RiteTemp"),
	RUSHAIR("Rush Air"),
	RUUD("Ruud"),
	RUPP("Rupp"),
	SAMSUNG("Samsung"),
	SANYO("Sanyo"),
	SEARS("Sears"),
	SEMCO("Semco"),
	SERIES16("Series 16"),
	SHARP("Sharp"),
	SIMONAIRE("Simonaire"),
	SINGER("Singer"),
	SKYLINE("Skyline"),
	SKYMARK("Skymark"),
	SLANTFIN("Slant Fin"),
	SMITH("Smith"),
	SNYDERGENERAL("Snyder General"),
	SOLEUSOLEUS("Soleus oleus"),
	SPACERAY("Space-Ray"),
	SPECIFICSYSTEMS("Specific Systems"),
	SPOTCOOLERS("Spot Coolers"),
	SQUARED("Square D"),
	STATEINDUSTRIES("State Industries"),
	STEWARTWARNER("Stewart-Warner"),
	SUNBELT("Sunbelt"),
	SUNBURST("Sunburst"),
	SUNDIAL("Sundial"),
	SUNGLOW("Sun Glow"),
	SURECOMFORT("SureComfort"),
	SUSSMAN("Sussman"),
	TAPPAN("Tappan"),
	TECUMSEH("Tecumseh"),
	TECHNICALSYSTEMS("Technical Systems"),
	TELEDYNELAARS("Teledyne Laars"),
	TEMPSTAR("Tempstar"),
	TEMTROL("Temtrol"),
	TEXACO("Texaco"),
	THERMODYNAMICS("Thermo-Dynamics"),
	THERMOFLO("Thermoflo"),
	THERMOPRIDE("Thermo Pride"),
	TITANAIR("Titan Air"),
	TOPP("TOPP"),
	TRANE("Trane"),
	UNIONENERGY("Union Energy"),
	UNITEDCOOLAIR("United CoolAir"),
	UNIVERSAL("Universal"),
	USACOILAIR("USA Coil & Air"),
	UTICA("Utica"),
	VALLIANT("Valliant"),
	VIESSMANN("Viessmann"),
	VISION("Vision"),
	WATERFURNACE("Water Furnace"),
	WATERPIKTECHNOLOGIES("Waterpik Technologies"),
	WEATHERKING("Weatherking"),
	WEILMCLAIN("Weil-McLain"),
	WESCO("Wesco"),
	WESTAIR("Westair"),
	WESTINGHOUSE("Westinghouse"),
	WILLIAMS("Williams"),
	WILLIAMSONTHERMOFLO("Williamson ThermoFlo"),
	YORK("York"),
	ZONEAIRE("Zoneaire"),
	NULL("NULL");

	protected String name;
	
	Make(String name) 
	{
		this.name = name;
	}

	public String toString() {
		return this.name;
	}
	
	public static Make getEnumType(String text) {
		
		for(Make make:Make.values()) {
			if(make.toString().equals(text))
				return make;
		}
		return Make.NULL;
	}
	
	public static String[] toStringArray() {
		String[] makes = new String[Make.values().length];
		int i = 0;
		
		for(Make make:Make.values()) {
			makes[i] = make.toString();
			i++;
		}
		
		return makes;
	}
}
