package com.example.testspeechrecognizer;

public enum CommandsTranslateEnum {

	ATFOTO("AT FOTO", CommandsEnum.PHOTO),
	ATPHOTOS("AT PHOTOS",CommandsEnum.PHOTO),
	ADDPHOTO("ADD PHOTO",CommandsEnum.PHOTO),
	ADDPHOTOS("ADD PHOTOS",CommandsEnum.PHOTO),
	ADDAPHOTO("ADD A PHOTO",CommandsEnum.PHOTO),
	ADDFOTO("ADD FOTO",CommandsEnum.PHOTO),
	HADFOTO("HAD FOTO",CommandsEnum.PHOTO),
	HADPHOTOS("HAD PHOTOS",CommandsEnum.PHOTO),
	ADDNEW("ADD NEW",CommandsEnum.ADDNEW),
	ATNEW("AT NEW",CommandsEnum.ADDNEW),
	AVENUE("AVENUE",CommandsEnum.ADDNEW),
	ADDANEW("ADD A NEW",CommandsEnum.ADDNEW),
	ADDNU("ADD NU",CommandsEnum.ADDNEW),
	ADDKNEW("ADD KNEW",CommandsEnum.ADDNEW),
	ADDNOUS("ADD NOUS",CommandsEnum.ADDNEW),
	ADDNUDE("ADD NUDE",CommandsEnum.ADDNEW),
	ATNU("AT NU",CommandsEnum.ADDNEW),
	ATKNEW("AT KNEW",CommandsEnum.ADDNEW),
	ATNOUS("AT NOUS",CommandsEnum.ADDNEW),
	ATNUDE("AT NUDE",CommandsEnum.ADDNEW),
	HADNEW("HAD NEW",CommandsEnum.ADDNEW),
	HADNU("HAD NU",CommandsEnum.ADDNEW),
	HADKNEW("HAD KNEW",CommandsEnum.ADDNEW),
	HADNOUS("HAD NOUS",CommandsEnum.ADDNEW),
	HADNUDE("HAD NUDE",CommandsEnum.ADDNEW),
	ADDAUDIO("ADD AUDIO",CommandsEnum.AUDIO),
	ADAUDIO("AD AUDIO",CommandsEnum.AUDIO),
	ADDCEREAL("ADD CEREAL",CommandsEnum.SERIAL),
	ATCEREAL("AT CEREAL",CommandsEnum.SERIAL),
	HADCEREAL("HAD CEREAL",CommandsEnum.SERIAL),
	ADDSERIAL("ADD SERIAL",CommandsEnum.SERIAL),
	ATSERIAL("AT SERIAL",CommandsEnum.SERIAL),
	HADSERIAL("HAD SERIAL",CommandsEnum.SERIAL),
	ADDSERIO("ADD SERIO",CommandsEnum.SERIAL),
	ATSERIO("AT SERIO",CommandsEnum.SERIAL),
	HADSERIO("HAD SERIO",CommandsEnum.SERIAL),
	ADDSURREAL("ADD SURREAL",CommandsEnum.SERIAL),
	ATSURREAL("AT SURREAL",CommandsEnum.SERIAL),
	HADSURREAL("HAD SURREAL",CommandsEnum.SERIAL),
	ADDSIRI("ADD SIRI",CommandsEnum.SERIAL),
	ATSIRI("AT SIRI",CommandsEnum.SERIAL),
	HADSIRI("HAD SIRI",CommandsEnum.SERIAL),
	ADDMODELNUMBER("ADD MODEL NUMBER",CommandsEnum.MODEL),
	ATMODELNUMBER("AT MODEL NUMBER",CommandsEnum.MODEL),
	HADMODELNUMBER("HAD MODEL NUMBER",CommandsEnum.MODEL),
	ADDMOBILENUMBER("ADD MOBILE NUMBER",CommandsEnum.MODEL),
	ATMOBILENUMBER("AT MOBILE NUMBER",CommandsEnum.MODEL),
	HADMOBILENUMBER("HAD MOBILE NUMBER",CommandsEnum.MODEL),
	ADDLOCATION("ADD LOCATION",CommandsEnum.LOCATION),
	ATLOCATION("AT LOCATION",CommandsEnum.LOCATION),
	HADLOCATION("HAD LOCATION",CommandsEnum.LOCATION),
	ADDLOCATIONS("ADD LOCATIONS",CommandsEnum.LOCATION),
	ATLOCATIONS("AT LOCATIONS",CommandsEnum.LOCATION),
	HADLOCATIONS("HAD LOCATIONS",CommandsEnum.LOCATION),
	ADDMANUFACTURER("ADD MANUFACTURER",CommandsEnum.MAKE),
	ATMANUFACTURER("AT MANUFACTURER",CommandsEnum.MAKE),
	HADMANUFACTURER("HAD MANUFACTURER",CommandsEnum.MAKE),
	ADDMANUFACTURE("ADD MANUFACTURE",CommandsEnum.MAKE),
	ATMANUFACTURE("AT MANUFACTURE",CommandsEnum.MAKE),
	HADMANUFACTURE("HAD MANUFACTURE",CommandsEnum.MAKE),
	ADDMANUFACTURED("ADD MANUFACTURED",CommandsEnum.MAKE),
	ATMANUFACTURED("AT MANUFACTURED",CommandsEnum.MAKE),
	HADMANUFACTURED("HAD MANUFACTURED",CommandsEnum.MAKE),
	ADDMANUFACTURES("ADD MANUFACTURES",CommandsEnum.MAKE),
	ATMANUFACTURES("AT MANUFACTURES",CommandsEnum.MAKE),
	HADMANUFACTURES("HAD MANUFACTURES",CommandsEnum.MAKE),
	ADMISSION("ADMISSION",CommandsEnum.MEASURE),
	ANDMEASURE("AND MEASURE",CommandsEnum.MEASURE),
	ADDMEASURED("ADD MEASURED",CommandsEnum.MEASURE),
	ADMISSIONS("ADMISSIONS",CommandsEnum.MEASURE),
	ANDMEASURED("AND MEASURED",CommandsEnum.MEASURE),
	ADUNIT_ID("AD UNIT ID",CommandsEnum.UNITID),
	ADDUNIT_ID("ADD UNIT ID",CommandsEnum.UNITID),
	ADUNITID("AD UNITID",CommandsEnum.UNITID),
	ANDUNITID("AND UNIT ID",CommandsEnum.UNITID),
	ADDUNITID("ADD UNITID", CommandsEnum.UNITID);

	private String heardWord;
	private CommandsEnum cEnum;
	
	CommandsTranslateEnum(String heardWord, CommandsEnum cEnum) {
		this.heardWord = heardWord;
		this.cEnum = cEnum;
	}
	
	public String getHeardWord() {
		return this.heardWord;
	}
	
	public CommandsEnum getCommandEnum() {
		return this.cEnum;
	}
}
